/**
 * Static WC2026 squad data.
 * Keyed by 3-letter team code (uppercase).
 * Players listed by position: GK, DEF, MID, FWD.
 */
export interface SquadPlayer { name: string; pos: 'GK' | 'DEF' | 'MID' | 'FWD' }
export type SquadMap = Record<string, SquadPlayer[]>

export const SQUADS: SquadMap = {
  CAN: [
    { name: 'Dayne St. Clair',     pos: 'GK'  },
    { name: 'Maxime Crépeau',      pos: 'GK'  },
    { name: 'Owen Goodman',        pos: 'GK'  },
    { name: 'Alistair Johnston',   pos: 'DEF' },
    { name: 'Luc de Fougerolles', pos: 'DEF' },
    { name: 'Alfie Jones',        pos: 'DEF' },
    { name: 'Joel Waterman',      pos: 'DEF' },
    { name: 'Derek Cornelius',    pos: 'DEF' },
    { name: 'Moïse Bombito',      pos: 'DEF' },
    { name: 'Alphonso Davies',    pos: 'DEF' },
    { name: 'Richie Laryea',      pos: 'DEF' },
    { name: 'Niko Sigur',         pos: 'DEF' },
    { name: 'Mathieu Choinière',  pos: 'MID' },
    { name: 'Stephen Eustáquio', pos: 'MID' },
    { name: 'Ismaël Koné',        pos: 'MID' },
    { name: 'Liam Millar',        pos: 'MID' },
    { name: 'Jacob Shaffelburg',  pos: 'MID' },
    { name: 'Tajon Buchanan',     pos: 'MID' },
    { name: 'Ali Ahmed',          pos: 'MID' },
    { name: 'Jonathan Osorio',    pos: 'MID' },
    { name: 'Nathan Saliba',      pos: 'MID' },
    { name: 'Cyle Larin',         pos: 'FWD' },
    { name: 'Jonathan David',     pos: 'FWD' },
    { name: 'Tani Oluwaseyi',     pos: 'FWD' },
    { name: 'Promise David',      pos: 'FWD' },
  ],
  USA: [
    { name: 'Matt Turner',          pos: 'GK'  },
    { name: 'Patrick Schulte',      pos: 'GK'  },
    { name: 'Ethan Horvath',        pos: 'GK'  },
    { name: 'Sergino Dest',         pos: 'DEF' },
    { name: 'Joe Scally',           pos: 'DEF' },
    { name: 'Tim Ream',             pos: 'DEF' },
    { name: 'Chris Richards',       pos: 'DEF' },
    { name: 'Miles Robinson',       pos: 'DEF' },
    { name: 'Antonee Robinson',     pos: 'DEF' },
    { name: 'Walker Zimmerman',     pos: 'DEF' },
    { name: 'Cameron Carter-Vickers', pos: 'DEF' },
    { name: 'Tyler Adams',          pos: 'MID' },
    { name: 'Weston McKennie',      pos: 'MID' },
    { name: 'Yunus Musah',          pos: 'MID' },
    { name: 'Luca de la Torre',     pos: 'MID' },
    { name: 'Malik Tillman',        pos: 'MID' },
    { name: 'Gio Reyna',            pos: 'MID' },
    { name: 'Brenden Aaronson',     pos: 'MID' },
    { name: 'Christian Pulisic',    pos: 'FWD' },
    { name: 'Josh Sargent',         pos: 'FWD' },
    { name: 'Folarin Balogun',      pos: 'FWD' },
    { name: 'Tim Weah',             pos: 'FWD' },
    { name: 'Ricardo Pepi',         pos: 'FWD' },
  ],
  MEX: [
    { name: 'Guillermo Ochoa',       pos: 'GK'  },
    { name: 'Luis Malagón',          pos: 'GK'  },
    { name: 'Carlos Acevedo',        pos: 'GK'  },
    { name: 'César Montes',          pos: 'DEF' },
    { name: 'Jesús Angulo',          pos: 'DEF' },
    { name: 'Jorge Sánchez',         pos: 'DEF' },
    { name: 'Gerardo Arteaga',       pos: 'DEF' },
    { name: 'Johan Vásquez',         pos: 'DEF' },
    { name: 'Kevin Álvarez',         pos: 'DEF' },
    { name: 'Luis Romo',             pos: 'MID' },
    { name: 'Edson Álvarez',         pos: 'MID' },
    { name: 'Carlos Rodríguez',      pos: 'MID' },
    { name: 'Alexis Vega',           pos: 'MID' },
    { name: 'Orbelin Pineda',        pos: 'MID' },
    { name: 'Uriel Antuna',          pos: 'MID' },
    { name: 'Roberto Alvarado',      pos: 'MID' },
    { name: 'Henry Martín',          pos: 'FWD' },
    { name: 'Raúl Jiménez',          pos: 'FWD' },
    { name: 'Hirving Lozano',        pos: 'FWD' },
    { name: 'Santiago Giménez',      pos: 'FWD' },
    { name: 'Julián Quiñones',       pos: 'FWD' },
  ],
  ARG: [
    { name: 'Emiliano Martínez',    pos: 'GK'  },
    { name: 'Geronimo Rulli',        pos: 'GK'  },
    { name: 'Walter Benitez',        pos: 'GK'  },
    { name: 'Nahuel Molina',         pos: 'DEF' },
    { name: 'Gonzalo Montiel',       pos: 'DEF' },
    { name: 'Cristian Romero',       pos: 'DEF' },
    { name: 'Lisandro Martínez',     pos: 'DEF' },
    { name: 'Nicolás Otamendi',      pos: 'DEF' },
    { name: 'Marcos Acuña',          pos: 'DEF' },
    { name: 'Nicolás Tagliafico',    pos: 'DEF' },
    { name: 'Rodrigo De Paul',       pos: 'MID' },
    { name: 'Leandro Paredes',       pos: 'MID' },
    { name: 'Enzo Fernández',        pos: 'MID' },
    { name: 'Alexis Mac Allister',   pos: 'MID' },
    { name: 'Giovani Lo Celso',      pos: 'MID' },
    { name: 'Exequiel Palacios',     pos: 'MID' },
    { name: 'Lionel Messi',          pos: 'FWD' },
    { name: 'Lautaro Martínez',      pos: 'FWD' },
    { name: 'Julián Álvarez',        pos: 'FWD' },
    { name: 'Ángel Di María',        pos: 'FWD' },
    { name: 'Nicolás González',      pos: 'FWD' },
    { name: 'Paulo Dybala',          pos: 'FWD' },
  ],
  BRA: [
    { name: 'Alisson',               pos: 'GK'  },
    { name: 'Ederson',               pos: 'GK'  },
    { name: 'Bento',                 pos: 'GK'  },
    { name: 'Éder Militão',          pos: 'DEF' },
    { name: 'Marquinhos',            pos: 'DEF' },
    { name: 'Gabriel Magalhães',     pos: 'DEF' },
    { name: 'Danilo',                pos: 'DEF' },
    { name: 'Wendell',               pos: 'DEF' },
    { name: 'Alex Telles',           pos: 'DEF' },
    { name: 'Casemiro',              pos: 'MID' },
    { name: 'Bruno Guimarães',       pos: 'MID' },
    { name: 'Lucas Paquetá',         pos: 'MID' },
    { name: 'Gerson',                pos: 'MID' },
    { name: 'Andreas Pereira',       pos: 'MID' },
    { name: 'Vinicius Jr.',          pos: 'FWD' },
    { name: 'Rodrygo',               pos: 'FWD' },
    { name: 'Raphinha',              pos: 'FWD' },
    { name: 'Gabriel Martinelli',    pos: 'FWD' },
    { name: 'Gabriel Jesus',         pos: 'FWD' },
    { name: 'Endrick',               pos: 'FWD' },
    { name: 'Savinho',               pos: 'FWD' },
  ],
  FRA: [
    { name: 'Mike Maignan',          pos: 'GK'  },
    { name: 'Alphonse Areola',       pos: 'GK'  },
    { name: 'Brice Samba',           pos: 'GK'  },
    { name: 'Jules Koundé',          pos: 'DEF' },
    { name: 'Dayot Upamecano',       pos: 'DEF' },
    { name: 'William Saliba',        pos: 'DEF' },
    { name: 'Ibrahima Konaté',       pos: 'DEF' },
    { name: 'Benjamin Pavard',       pos: 'DEF' },
    { name: 'Theo Hernández',        pos: 'DEF' },
    { name: 'N\'Golo Kanté',         pos: 'MID' },
    { name: 'Aurélien Tchouaméni',   pos: 'MID' },
    { name: 'Adrien Rabiot',         pos: 'MID' },
    { name: 'Eduardo Camavinga',     pos: 'MID' },
    { name: 'Youssouf Fofana',       pos: 'MID' },
    { name: 'Kylian Mbappé',         pos: 'FWD' },
    { name: 'Antoine Griezmann',     pos: 'FWD' },
    { name: 'Olivier Giroud',        pos: 'FWD' },
    { name: 'Ousmane Dembélé',       pos: 'FWD' },
    { name: 'Marcus Thuram',         pos: 'FWD' },
    { name: 'Randal Kolo Muani',     pos: 'FWD' },
    { name: 'Bradley Barcola',       pos: 'FWD' },
  ],
  ENG: [
    { name: 'Jordan Pickford',       pos: 'GK'  },
    { name: 'Dean Henderson',        pos: 'GK'  },
    { name: 'Aaron Ramsdale',        pos: 'GK'  },
    { name: 'Reece James',           pos: 'DEF' },
    { name: 'Trent Alexander-Arnold',pos: 'DEF' },
    { name: 'John Stones',           pos: 'DEF' },
    { name: 'Harry Maguire',         pos: 'DEF' },
    { name: 'Marc Guehi',            pos: 'DEF' },
    { name: 'Luke Shaw',             pos: 'DEF' },
    { name: 'Kieran Trippier',       pos: 'DEF' },
    { name: 'Declan Rice',           pos: 'MID' },
    { name: 'Jude Bellingham',       pos: 'MID' },
    { name: 'Kobbie Mainoo',         pos: 'MID' },
    { name: 'Conor Gallagher',       pos: 'MID' },
    { name: 'Adam Wharton',          pos: 'MID' },
    { name: 'Harry Kane',            pos: 'FWD' },
    { name: 'Phil Foden',            pos: 'FWD' },
    { name: 'Bukayo Saka',           pos: 'FWD' },
    { name: 'Marcus Rashford',       pos: 'FWD' },
    { name: 'Jarrod Bowen',          pos: 'FWD' },
    { name: 'Ollie Watkins',         pos: 'FWD' },
    { name: 'Cole Palmer',           pos: 'FWD' },
    { name: 'Anthony Gordon',        pos: 'FWD' },
  ],
  ESP: [
    { name: 'Unai Simón',            pos: 'GK'  },
    { name: 'David Raya',            pos: 'GK'  },
    { name: 'Robert Sánchez',        pos: 'GK'  },
    { name: 'Dani Carvajal',         pos: 'DEF' },
    { name: 'Nacho',                 pos: 'DEF' },
    { name: 'Robin Le Normand',      pos: 'DEF' },
    { name: 'Aymeric Laporte',       pos: 'DEF' },
    { name: 'Alejandro Grimaldo',    pos: 'DEF' },
    { name: 'Marc Cucurella',        pos: 'DEF' },
    { name: 'Rodrigo',               pos: 'MID' },
    { name: 'Fabián Ruiz',           pos: 'MID' },
    { name: 'Pedri',                 pos: 'MID' },
    { name: 'Dani Olmo',             pos: 'MID' },
    { name: 'Martín Zubimendi',      pos: 'MID' },
    { name: 'Mikel Merino',          pos: 'MID' },
    { name: 'Álvaro Morata',         pos: 'FWD' },
    { name: 'Lamine Yamal',          pos: 'FWD' },
    { name: 'Nico Williams',         pos: 'FWD' },
    { name: 'Ferran Torres',         pos: 'FWD' },
    { name: 'Mikel Oyarzabal',       pos: 'FWD' },
    { name: 'Ayoze Pérez',           pos: 'FWD' },
  ],
  GER: [
    { name: 'Manuel Neuer',          pos: 'GK'  },
    { name: 'Marc-André ter Stegen', pos: 'GK'  },
    { name: 'Oliver Baumann',        pos: 'GK'  },
    { name: 'Joshua Kimmich',        pos: 'DEF' },
    { name: 'Antonio Rüdiger',       pos: 'DEF' },
    { name: 'Jonathan Tah',          pos: 'DEF' },
    { name: 'Nico Schlotterbeck',    pos: 'DEF' },
    { name: 'Maximilian Mittelstädt',pos: 'DEF' },
    { name: 'David Raum',            pos: 'DEF' },
    { name: 'Leon Goretzka',         pos: 'MID' },
    { name: 'İlkay Gündoğan',        pos: 'MID' },
    { name: 'Robert Andrich',        pos: 'MID' },
    { name: 'Florian Wirtz',         pos: 'MID' },
    { name: 'Jamal Musiala',         pos: 'MID' },
    { name: 'Kai Havertz',           pos: 'FWD' },
    { name: 'Thomas Müller',         pos: 'FWD' },
    { name: 'Leroy Sané',            pos: 'FWD' },
    { name: 'Serge Gnabry',          pos: 'FWD' },
    { name: 'Niclas Füllkrug',       pos: 'FWD' },
    { name: 'Deniz Undav',           pos: 'FWD' },
  ],
  POR: [
    { name: 'Rui Patrício',          pos: 'GK'  },
    { name: 'Diogo Costa',           pos: 'GK'  },
    { name: 'José Sá',               pos: 'GK'  },
    { name: 'João Cancelo',          pos: 'DEF' },
    { name: 'Nuno Mendes',           pos: 'DEF' },
    { name: 'Rúben Dias',            pos: 'DEF' },
    { name: 'Pepe',                  pos: 'DEF' },
    { name: 'Danilo Pereira',        pos: 'DEF' },
    { name: 'António Silva',         pos: 'DEF' },
    { name: 'Bernardo Silva',        pos: 'MID' },
    { name: 'Vitinha',               pos: 'MID' },
    { name: 'João Neves',            pos: 'MID' },
    { name: 'Rúben Neves',           pos: 'MID' },
    { name: 'Bruno Fernandes',       pos: 'MID' },
    { name: 'João Félix',            pos: 'FWD' },
    { name: 'Cristiano Ronaldo',     pos: 'FWD' },
    { name: 'Rafael Leão',           pos: 'FWD' },
    { name: 'Pedro Neto',            pos: 'FWD' },
    { name: 'Gonçalo Ramos',         pos: 'FWD' },
    { name: 'Francisco Conceição',   pos: 'FWD' },
  ],
  NED: [
    { name: 'Mark Flekken',          pos: 'GK'  },
    { name: 'Bart Verbruggen',       pos: 'GK'  },
    { name: 'Justin Bijlow',         pos: 'GK'  },
    { name: 'Denzel Dumfries',       pos: 'DEF' },
    { name: 'Virgil van Dijk',       pos: 'DEF' },
    { name: 'Stefan de Vrij',        pos: 'DEF' },
    { name: 'Nathan Aké',            pos: 'DEF' },
    { name: 'Jurriën Timber',        pos: 'DEF' },
    { name: 'Matthijs de Ligt',      pos: 'DEF' },
    { name: 'Frenkie de Jong',       pos: 'MID' },
    { name: 'Teun Koopmeiners',      pos: 'MID' },
    { name: 'Ryan Gravenberch',      pos: 'MID' },
    { name: 'Xavi Simons',           pos: 'MID' },
    { name: 'Marten de Roon',        pos: 'MID' },
    { name: 'Memphis Depay',         pos: 'FWD' },
    { name: 'Donyell Malen',         pos: 'FWD' },
    { name: 'Steven Bergwijn',       pos: 'FWD' },
    { name: 'Wout Weghorst',         pos: 'FWD' },
    { name: 'Cody Gakpo',            pos: 'FWD' },
    { name: 'Brian Brobbey',         pos: 'FWD' },
  ],
}

/** Convenience: get squad for a team code, grouped by position. */
export function getSquadByPosition(code: string) {
  const players = SQUADS[code.toUpperCase()] ?? []
  return {
    GK:  players.filter(p => p.pos === 'GK'),
    DEF: players.filter(p => p.pos === 'DEF'),
    MID: players.filter(p => p.pos === 'MID'),
    FWD: players.filter(p => p.pos === 'FWD'),
    total: players.length,
  }
}
