/**
 * Static WC2026 squad data.
 * Keyed by 3-letter team code (uppercase) — matches seed-db codes.
 * Players listed by position: GK, DEF, MID, FWD.
 */
export interface SquadPlayer { name: string; pos: 'GK' | 'DEF' | 'MID' | 'FWD' }
export type SquadMap = Record<string, SquadPlayer[]>

export const SQUADS: SquadMap = {

  // ── Group A ──────────────────────────────────────────────────────────────
  MEX: [
    { name: 'Guillermo Ochoa',        pos: 'GK'  },
    { name: 'Luis Malagon',           pos: 'GK'  },
    { name: 'Carlos Acevedo',         pos: 'GK'  },
    { name: 'Cesar Montes',           pos: 'DEF' },
    { name: 'Jesus Angulo',           pos: 'DEF' },
    { name: 'Jorge Sanchez',          pos: 'DEF' },
    { name: 'Gerardo Arteaga',        pos: 'DEF' },
    { name: 'Johan Vasquez',          pos: 'DEF' },
    { name: 'Luis Romo',              pos: 'MID' },
    { name: 'Edson Alvarez',          pos: 'MID' },
    { name: 'Carlos Rodriguez',       pos: 'MID' },
    { name: 'Alexis Vega',            pos: 'MID' },
    { name: 'Roberto Alvarado',       pos: 'MID' },
    { name: 'Hirving Lozano',         pos: 'FWD' },
    { name: 'Henry Martin',           pos: 'FWD' },
    { name: 'Raul Jimenez',           pos: 'FWD' },
    { name: 'Santiago Gimenez',       pos: 'FWD' },
  ],
  ZAF: [
    { name: 'Ronwen Williams',        pos: 'GK'  },
    { name: 'Veli Mothwa',            pos: 'GK'  },
    { name: 'Siyanda Xulu',           pos: 'DEF' },
    { name: 'Rushine De Reuck',       pos: 'DEF' },
    { name: 'Reeve Frosler',          pos: 'DEF' },
    { name: 'Innocent Maela',         pos: 'DEF' },
    { name: 'Sifiso Hlanti',          pos: 'DEF' },
    { name: 'Teboho Mokoena',         pos: 'MID' },
    { name: 'Keagan Dolly',           pos: 'MID' },
    { name: 'Ethan Ngoyi',            pos: 'MID' },
    { name: 'Evidence Makgopa',       pos: 'FWD' },
    { name: 'Percy Tau',              pos: 'FWD' },
    { name: 'Lyle Foster',            pos: 'FWD' },
    { name: 'Bongani Zungu',          pos: 'MID' },
  ],
  KOR: [
    { name: 'Kim Seung-gyu',          pos: 'GK'  },
    { name: 'Jo Hyeon-woo',           pos: 'GK'  },
    { name: 'Kim Min-jae',            pos: 'DEF' },
    { name: 'Kim Young-gwon',         pos: 'DEF' },
    { name: 'Lee Yong',               pos: 'DEF' },
    { name: 'Kim Jin-su',             pos: 'DEF' },
    { name: 'Jung Woo-young',         pos: 'MID' },
    { name: 'Lee Jae-sung',           pos: 'MID' },
    { name: 'Hwang In-beom',          pos: 'MID' },
    { name: 'Lee Kang-in',            pos: 'MID' },
    { name: 'Son Heung-min',          pos: 'FWD' },
    { name: 'Hwang Hee-chan',         pos: 'FWD' },
    { name: 'Cho Gue-sung',           pos: 'FWD' },
    { name: 'Oh Hyeon-gyu',           pos: 'FWD' },
  ],
  CZE: [
    { name: 'Jiri Pavlenka',          pos: 'GK'  },
    { name: 'Tomas Vaclik',           pos: 'GK'  },
    { name: 'Tomas Holes',            pos: 'DEF' },
    { name: 'Ondrej Celustka',        pos: 'DEF' },
    { name: 'David Zima',             pos: 'DEF' },
    { name: 'Jan Boril',              pos: 'DEF' },
    { name: 'Ladislav Krejci',        pos: 'DEF' },
    { name: 'Tomas Soucek',           pos: 'MID' },
    { name: 'Alex Kral',              pos: 'MID' },
    { name: 'Lukas Provod',           pos: 'MID' },
    { name: 'Jakub Pesek',            pos: 'MID' },
    { name: 'Patrik Schick',          pos: 'FWD' },
    { name: 'Adam Hlozek',            pos: 'FWD' },
    { name: 'Ondrej Lingr',           pos: 'FWD' },
    { name: 'Lukas Julis',            pos: 'FWD' },
  ],

  // ── Group B ──────────────────────────────────────────────────────────────
  CAN: [
    { name: 'Dayne St. Clair',        pos: 'GK'  },
    { name: 'Maxime Crepeau',         pos: 'GK'  },
    { name: 'Alistair Johnston',      pos: 'DEF' },
    { name: 'Alphonso Davies',        pos: 'DEF' },
    { name: 'Richie Laryea',          pos: 'DEF' },
    { name: 'Derek Cornelius',        pos: 'DEF' },
    { name: 'Moise Bombito',          pos: 'DEF' },
    { name: 'Stephen Eustaquio',      pos: 'MID' },
    { name: 'Ismael Kone',            pos: 'MID' },
    { name: 'Jonathan Osorio',        pos: 'MID' },
    { name: 'Tajon Buchanan',         pos: 'MID' },
    { name: 'Jonathan David',         pos: 'FWD' },
    { name: 'Cyle Larin',             pos: 'FWD' },
    { name: 'Tani Oluwaseyi',         pos: 'FWD' },
    { name: 'Jacob Shaffelburg',      pos: 'MID' },
  ],
  BIH: [
    { name: 'Ibrahim Sehic',          pos: 'GK'  },
    { name: 'Nikola Vasilj',          pos: 'GK'  },
    { name: 'Sead Kolasinac',         pos: 'DEF' },
    { name: 'Anel Ahmedhodžic',       pos: 'DEF' },
    { name: 'Ervin Zukanovic',        pos: 'DEF' },
    { name: 'Amar Dedic',             pos: 'DEF' },
    { name: 'Miralem Pjanic',         pos: 'MID' },
    { name: 'Gojko Cimirot',          pos: 'MID' },
    { name: 'Haris Tabakovic',        pos: 'MID' },
    { name: 'Edin Dzeko',             pos: 'FWD' },
    { name: 'Ermedin Demirovic',      pos: 'FWD' },
    { name: 'Armin Hodzic',           pos: 'FWD' },
    { name: 'Benjamin Tahirovic',     pos: 'MID' },
  ],
  QAT: [
    { name: 'Meshaal Barsham',        pos: 'GK'  },
    { name: 'Yousef Hassan',          pos: 'GK'  },
    { name: 'Pedro Miguel',           pos: 'DEF' },
    { name: 'Bassam Al-Rawi',         pos: 'DEF' },
    { name: 'Homam Ahmed',            pos: 'DEF' },
    { name: 'Abdelkarim Hassan',      pos: 'DEF' },
    { name: 'Karim Boudiaf',          pos: 'MID' },
    { name: 'Assim Madibo',           pos: 'MID' },
    { name: 'Akram Afif',             pos: 'MID' },
    { name: 'Hassan Al-Haydos',       pos: 'MID' },
    { name: 'Almoez Ali',             pos: 'FWD' },
    { name: 'Mohammed Muntari',       pos: 'FWD' },
    { name: 'Yusuf Abdurisag',        pos: 'FWD' },
  ],
  SUI: [
    { name: 'Yann Sommer',            pos: 'GK'  },
    { name: 'Gregor Kobel',           pos: 'GK'  },
    { name: 'Fabian Schar',           pos: 'DEF' },
    { name: 'Manuel Akanji',          pos: 'DEF' },
    { name: 'Ricardo Rodriguez',      pos: 'DEF' },
    { name: 'Silvan Widmer',          pos: 'DEF' },
    { name: 'Granit Xhaka',           pos: 'MID' },
    { name: 'Remo Freuler',           pos: 'MID' },
    { name: 'Denis Zakaria',          pos: 'MID' },
    { name: 'Ruben Vargas',           pos: 'MID' },
    { name: 'Xherdan Shaqiri',        pos: 'FWD' },
    { name: 'Breel Embolo',           pos: 'FWD' },
    { name: 'Noah Okafor',            pos: 'FWD' },
    { name: 'Zeki Amdouni',           pos: 'FWD' },
  ],

  // ── Group C ──────────────────────────────────────────────────────────────
  HTI: [
    { name: 'Josue Duverger',         pos: 'GK'  },
    { name: 'Donovan Pines',          pos: 'DEF' },
    { name: 'Mechack Jerome',         pos: 'DEF' },
    { name: 'Steeven Saba',           pos: 'DEF' },
    { name: 'Edson Fleurival',        pos: 'MID' },
    { name: 'Frantzdy Pierrot',       pos: 'MID' },
    { name: 'Kevin Lafrance',         pos: 'MID' },
    { name: 'Ronaldo Carton',         pos: 'MID' },
    { name: 'Duckens Nazon',          pos: 'FWD' },
    { name: 'Frantz Pierrot',         pos: 'FWD' },
    { name: 'Nicolas Janvier',        pos: 'FWD' },
  ],
  SCO: [
    { name: 'Angus Gunn',             pos: 'GK'  },
    { name: 'Craig Gordon',           pos: 'GK'  },
    { name: 'Andy Robertson',         pos: 'DEF' },
    { name: 'Grant Hanley',           pos: 'DEF' },
    { name: 'Scott McKenna',          pos: 'DEF' },
    { name: 'Anthony Ralston',        pos: 'DEF' },
    { name: 'John Souttar',           pos: 'DEF' },
    { name: 'Callum McGregor',        pos: 'MID' },
    { name: 'Scott McTominay',        pos: 'MID' },
    { name: 'Ryan Christie',          pos: 'MID' },
    { name: 'Billy Gilmour',          pos: 'MID' },
    { name: 'John McGinn',            pos: 'MID' },
    { name: 'Lyndon Dykes',           pos: 'FWD' },
    { name: 'Che Adams',              pos: 'FWD' },
    { name: 'Ryan Fraser',            pos: 'FWD' },
    { name: 'Stuart Armstrong',       pos: 'MID' },
  ],
  BRA: [
    { name: 'Alisson Becker',         pos: 'GK'  },
    { name: 'Ederson',                pos: 'GK'  },
    { name: 'Danilo',                 pos: 'DEF' },
    { name: 'Eder Militao',           pos: 'DEF' },
    { name: 'Marquinhos',             pos: 'DEF' },
    { name: 'Thiago Silva',           pos: 'DEF' },
    { name: 'Alex Sandro',            pos: 'DEF' },
    { name: 'Casemiro',               pos: 'MID' },
    { name: 'Lucas Paqueta',          pos: 'MID' },
    { name: 'Bruno Guimaraes',        pos: 'MID' },
    { name: 'Rodrygo',                pos: 'MID' },
    { name: 'Vinicius Jr.',           pos: 'FWD' },
    { name: 'Neymar Jr.',             pos: 'FWD' },
    { name: 'Richarlison',            pos: 'FWD' },
    { name: 'Raphinha',               pos: 'FWD' },
    { name: 'Gabriel Jesus',          pos: 'FWD' },
    { name: 'Gabriel Martinelli',     pos: 'FWD' },
  ],
  MAR: [
    { name: 'Yassine Bounou',         pos: 'GK'  },
    { name: 'Ahmed Tagnaouti',        pos: 'GK'  },
    { name: 'Achraf Hakimi',          pos: 'DEF' },
    { name: 'Nayef Aguerd',           pos: 'DEF' },
    { name: 'Romain Saiss',           pos: 'DEF' },
    { name: 'Noussair Mazraoui',      pos: 'DEF' },
    { name: 'Jawad El Yamiq',         pos: 'DEF' },
    { name: 'Sofyan Amrabat',         pos: 'MID' },
    { name: 'Azzedine Ounahi',        pos: 'MID' },
    { name: 'Ilias Chair',            pos: 'MID' },
    { name: 'Hakim Ziyech',           pos: 'FWD' },
    { name: 'Youssef En-Nesyri',      pos: 'FWD' },
    { name: 'Abde Ezzalzouli',        pos: 'FWD' },
    { name: 'Sofiane Boufal',         pos: 'FWD' },
    { name: 'Walid Cheddira',         pos: 'FWD' },
  ],

  // ── Group D ──────────────────────────────────────────────────────────────
  USA: [
    { name: 'Matt Turner',            pos: 'GK'  },
    { name: 'Patrick Schulte',        pos: 'GK'  },
    { name: 'Ethan Horvath',          pos: 'GK'  },
    { name: 'Sergino Dest',           pos: 'DEF' },
    { name: 'Joe Scally',             pos: 'DEF' },
    { name: 'Tim Ream',               pos: 'DEF' },
    { name: 'Chris Richards',         pos: 'DEF' },
    { name: 'Miles Robinson',         pos: 'DEF' },
    { name: 'Antonee Robinson',       pos: 'DEF' },
    { name: 'Walker Zimmerman',       pos: 'DEF' },
    { name: 'Tyler Adams',            pos: 'MID' },
    { name: 'Weston McKennie',        pos: 'MID' },
    { name: 'Yunus Musah',            pos: 'MID' },
    { name: 'Gio Reyna',              pos: 'MID' },
    { name: 'Brenden Aaronson',       pos: 'MID' },
    { name: 'Christian Pulisic',      pos: 'FWD' },
    { name: 'Josh Sargent',           pos: 'FWD' },
    { name: 'Folarin Balogun',        pos: 'FWD' },
    { name: 'Tim Weah',               pos: 'FWD' },
    { name: 'Ricardo Pepi',           pos: 'FWD' },
  ],
  PRY: [
    { name: 'Antony Silva',           pos: 'GK'  },
    { name: 'Alfredo Aguilar',        pos: 'GK'  },
    { name: 'Junior Alonso',          pos: 'DEF' },
    { name: 'Gustavo Gomez',          pos: 'DEF' },
    { name: 'Santiago Arzamendia',    pos: 'DEF' },
    { name: 'Robert Rojas',           pos: 'DEF' },
    { name: 'Fabian Balbuena',        pos: 'DEF' },
    { name: 'Miguel Almiron',         pos: 'MID' },
    { name: 'Richard Sanchez',        pos: 'MID' },
    { name: 'Mathias Villasanti',     pos: 'MID' },
    { name: 'Adam Bareiro',           pos: 'FWD' },
    { name: 'Antonio Sanabria',       pos: 'FWD' },
    { name: 'Julio Enciso',           pos: 'FWD' },
  ],
  AUS: [
    { name: 'Mat Ryan',               pos: 'GK'  },
    { name: 'Danny Vukovic',          pos: 'GK'  },
    { name: 'Milos Degenek',          pos: 'DEF' },
    { name: 'Bailey Wright',          pos: 'DEF' },
    { name: 'Aziz Behich',            pos: 'DEF' },
    { name: 'Kye Rowles',             pos: 'DEF' },
    { name: 'Jackson Irvine',         pos: 'MID' },
    { name: 'Aaron Mooy',             pos: 'MID' },
    { name: 'Riley McGree',           pos: 'MID' },
    { name: 'Ajdin Hrustic',          pos: 'MID' },
    { name: 'Mathew Leckie',          pos: 'FWD' },
    { name: 'Mitchell Duke',          pos: 'FWD' },
    { name: 'Craig Goodwin',          pos: 'FWD' },
    { name: 'Awer Mabil',             pos: 'FWD' },
  ],
  TUR: [
    { name: 'Altay Bayindir',         pos: 'GK'  },
    { name: 'Mert Gunok',             pos: 'GK'  },
    { name: 'Zeki Celik',             pos: 'DEF' },
    { name: 'Samet Akaydin',          pos: 'DEF' },
    { name: 'Merih Demiral',          pos: 'DEF' },
    { name: 'Ferdi Kadioglu',         pos: 'DEF' },
    { name: 'Hakan Calhanoglu',       pos: 'MID' },
    { name: 'Orkun Kokcu',            pos: 'MID' },
    { name: 'Salih Ozcan',            pos: 'MID' },
    { name: 'Arda Guler',             pos: 'MID' },
    { name: 'Kerem Akturkoglu',       pos: 'FWD' },
    { name: 'Baris Alper Yilmaz',     pos: 'FWD' },
    { name: 'Cenk Tosun',             pos: 'FWD' },
    { name: 'Yunus Akgun',            pos: 'FWD' },
  ],

  // ── Group E ──────────────────────────────────────────────────────────────
  GER: [
    { name: 'Manuel Neuer',           pos: 'GK'  },
    { name: 'Marc-Andre ter Stegen',  pos: 'GK'  },
    { name: 'Joshua Kimmich',         pos: 'DEF' },
    { name: 'Antonio Rudiger',        pos: 'DEF' },
    { name: 'Niklas Sule',            pos: 'DEF' },
    { name: 'David Raum',             pos: 'DEF' },
    { name: 'Leon Goretzka',          pos: 'MID' },
    { name: 'Ilkay Gundogan',         pos: 'MID' },
    { name: 'Kai Havertz',            pos: 'MID' },
    { name: 'Jamal Musiala',          pos: 'MID' },
    { name: 'Florian Wirtz',          pos: 'MID' },
    { name: 'Leroy Sane',             pos: 'FWD' },
    { name: 'Serge Gnabry',           pos: 'FWD' },
    { name: 'Thomas Muller',          pos: 'FWD' },
    { name: 'Niclas Fullkrug',        pos: 'FWD' },
  ],
  CUW: [
    { name: 'Eloy Room',              pos: 'GK'  },
    { name: 'Gianni Zuiverloon',      pos: 'DEF' },
    { name: 'Rangelo Janga',          pos: 'DEF' },
    { name: 'Jurickson Profar',       pos: 'MID' },
    { name: 'Leandro Bacuna',         pos: 'MID' },
    { name: 'Cuco Martina',           pos: 'DEF' },
    { name: 'Ryan Donk',              pos: 'DEF' },
    { name: 'Gevaro Nepomuceno',      pos: 'FWD' },
    { name: 'Gernot Trauner',         pos: 'DEF' },
    { name: 'Charlton Vicento',       pos: 'FWD' },
    { name: 'Tjaronn Chery',          pos: 'MID' },
  ],
  CIV: [
    { name: 'Yahia Fofana',           pos: 'GK'  },
    { name: 'Badra Ali Sangare',      pos: 'GK'  },
    { name: 'Serge Aurier',           pos: 'DEF' },
    { name: 'Willy Boly',             pos: 'DEF' },
    { name: 'Odilon Kossounou',       pos: 'DEF' },
    { name: 'Ghislain Konan',         pos: 'DEF' },
    { name: 'Franck Kessie',          pos: 'MID' },
    { name: 'Ibrahim Sangare',        pos: 'MID' },
    { name: 'Seko Fofana',            pos: 'MID' },
    { name: 'Simon Adingra',          pos: 'MID' },
    { name: 'Sebastien Haller',       pos: 'FWD' },
    { name: 'Nicolas Pepe',           pos: 'FWD' },
    { name: 'Wilfried Zaha',          pos: 'FWD' },
    { name: 'Maxwel Cornet',          pos: 'FWD' },
  ],
  ECU: [
    { name: 'Hernan Galindez',        pos: 'GK'  },
    { name: 'Alexander Dominguez',    pos: 'GK'  },
    { name: 'Piero Hincapie',         pos: 'DEF' },
    { name: 'Byron Castillo',         pos: 'DEF' },
    { name: 'Robert Arboleda',        pos: 'DEF' },
    { name: 'Xavier Arreaga',         pos: 'DEF' },
    { name: 'Felix Torres',           pos: 'DEF' },
    { name: 'Carlos Gruezo',          pos: 'MID' },
    { name: 'Moises Caicedo',         pos: 'MID' },
    { name: 'Jeremy Sarmiento',       pos: 'MID' },
    { name: 'Enner Valencia',         pos: 'FWD' },
    { name: 'Michael Estrada',        pos: 'FWD' },
    { name: 'Gonzalo Plata',          pos: 'FWD' },
    { name: 'Djorkaeff Reasco',       pos: 'FWD' },
  ],

  // ── Group F ──────────────────────────────────────────────────────────────
  NED: [
    { name: 'Bart Verbruggen',        pos: 'GK'  },
    { name: 'Mark Flekken',           pos: 'GK'  },
    { name: 'Virgil van Dijk',        pos: 'DEF' },
    { name: 'Denzel Dumfries',        pos: 'DEF' },
    { name: 'Nathan Ake',             pos: 'DEF' },
    { name: 'Jurrien Timber',         pos: 'DEF' },
    { name: 'Stefan de Vrij',         pos: 'DEF' },
    { name: 'Frenkie de Jong',        pos: 'MID' },
    { name: 'Teun Koopmeiners',       pos: 'MID' },
    { name: 'Ryan Gravenberch',       pos: 'MID' },
    { name: 'Xavi Simons',            pos: 'MID' },
    { name: 'Cody Gakpo',             pos: 'FWD' },
    { name: 'Memphis Depay',          pos: 'FWD' },
    { name: 'Donyell Malen',          pos: 'FWD' },
    { name: 'Wout Weghorst',          pos: 'FWD' },
    { name: 'Brian Brobbey',          pos: 'FWD' },
  ],
  JPN: [
    { name: 'Shuichi Gonda',          pos: 'GK'  },
    { name: 'Zion Suzuki',            pos: 'GK'  },
    { name: 'Maya Yoshida',           pos: 'DEF' },
    { name: 'Ko Itakura',             pos: 'DEF' },
    { name: 'Yuto Nagatomo',          pos: 'DEF' },
    { name: 'Hiroki Sakai',           pos: 'DEF' },
    { name: 'Wataru Endo',            pos: 'MID' },
    { name: 'Hidemasa Morita',        pos: 'MID' },
    { name: 'Daichi Kamada',          pos: 'MID' },
    { name: 'Takefusa Kubo',          pos: 'MID' },
    { name: 'Ao Tanaka',              pos: 'MID' },
    { name: 'Kaoru Mitoma',           pos: 'FWD' },
    { name: 'Ritsu Doan',             pos: 'FWD' },
    { name: 'Ayase Ueda',             pos: 'FWD' },
    { name: 'Keito Nakamura',         pos: 'FWD' },
  ],
  SWE: [
    { name: 'Robin Olsen',            pos: 'GK'  },
    { name: 'Karl-Johan Johnsson',    pos: 'GK'  },
    { name: 'Victor Lindelof',        pos: 'DEF' },
    { name: 'Marcus Danielson',       pos: 'DEF' },
    { name: 'Ludwig Augustinsson',    pos: 'DEF' },
    { name: 'Emil Krafth',            pos: 'DEF' },
    { name: 'Albin Ekdal',            pos: 'MID' },
    { name: 'Kristoffer Olsson',      pos: 'MID' },
    { name: 'Dejan Kulusevski',       pos: 'MID' },
    { name: 'Emil Forsberg',          pos: 'MID' },
    { name: 'Alexander Isak',         pos: 'FWD' },
    { name: 'Jordan Larsson',         pos: 'FWD' },
    { name: 'Viktor Gyokeres',        pos: 'FWD' },
    { name: 'Anthony Elanga',         pos: 'FWD' },
  ],
  TUN: [
    { name: 'Aymen Dahmen',           pos: 'GK'  },
    { name: 'Mouez Hassen',           pos: 'GK'  },
    { name: 'Dylan Bronn',            pos: 'DEF' },
    { name: 'Montassar Talbi',        pos: 'DEF' },
    { name: 'Ali Maaloul',            pos: 'DEF' },
    { name: 'Wajdi Kechrida',         pos: 'DEF' },
    { name: 'Aissa Laidouni',         pos: 'MID' },
    { name: 'Hannibal Mejbri',        pos: 'MID' },
    { name: 'Ellyes Skhiri',          pos: 'MID' },
    { name: 'Youssef Msakni',         pos: 'FWD' },
    { name: 'Seifeddine Jaziri',      pos: 'FWD' },
    { name: 'Wahbi Khazri',           pos: 'FWD' },
    { name: 'Naim Sliti',             pos: 'FWD' },
  ],

  // ── Group G ──────────────────────────────────────────────────────────────
  IRN: [
    { name: 'Alireza Beiranvand',     pos: 'GK'  },
    { name: 'Hossein Hosseini',       pos: 'GK'  },
    { name: 'Shoja Khalilzadeh',      pos: 'DEF' },
    { name: 'Milad Mohammadi',        pos: 'DEF' },
    { name: 'Ramin Rezaeian',         pos: 'DEF' },
    { name: 'Majid Hosseini',         pos: 'DEF' },
    { name: 'Saeid Ezatolahi',        pos: 'MID' },
    { name: 'Ahmad Noorollahi',       pos: 'MID' },
    { name: 'Ali Gholizadeh',         pos: 'MID' },
    { name: 'Mehdi Taremi',           pos: 'FWD' },
    { name: 'Sardar Azmoun',          pos: 'FWD' },
    { name: 'Allahyar Sayyadmanesh',  pos: 'FWD' },
    { name: 'Karim Ansarifard',       pos: 'FWD' },
  ],
  NZL: [
    { name: 'Oliver Sail',            pos: 'GK'  },
    { name: 'Max Crocombe',           pos: 'GK'  },
    { name: 'Winston Reid',           pos: 'DEF' },
    { name: 'Liberato Cacace',        pos: 'DEF' },
    { name: 'Tommy Smith',            pos: 'DEF' },
    { name: 'Michael Boxall',         pos: 'DEF' },
    { name: 'Joe Bell',               pos: 'MID' },
    { name: 'Ryan Thomas',            pos: 'MID' },
    { name: 'Callum McCowatt',        pos: 'MID' },
    { name: 'Marco Rojas',            pos: 'MID' },
    { name: 'Chris Wood',             pos: 'FWD' },
    { name: 'Matthew Garbett',        pos: 'FWD' },
    { name: 'Elijah Just',            pos: 'MID' },
  ],
  BEL: [
    { name: 'Thibaut Courtois',       pos: 'GK'  },
    { name: 'Simon Mignolet',         pos: 'GK'  },
    { name: 'Toby Alderweireld',      pos: 'DEF' },
    { name: 'Jan Vertonghen',         pos: 'DEF' },
    { name: 'Thomas Meunier',         pos: 'DEF' },
    { name: 'Zeno Debast',            pos: 'DEF' },
    { name: 'Kevin De Bruyne',        pos: 'MID' },
    { name: 'Youri Tielemans',        pos: 'MID' },
    { name: 'Amadou Onana',           pos: 'MID' },
    { name: 'Leandro Trossard',       pos: 'MID' },
    { name: 'Jeremy Doku',            pos: 'MID' },
    { name: 'Romelu Lukaku',          pos: 'FWD' },
    { name: 'Lois Openda',            pos: 'FWD' },
    { name: 'Dodi Lukebakio',         pos: 'FWD' },
  ],
  EGY: [
    { name: 'Mohamed El-Shenawy',     pos: 'GK'  },
    { name: 'Ahmed El-Shenawy',       pos: 'GK'  },
    { name: 'Ahmed Hegazi',           pos: 'DEF' },
    { name: 'Omar Kamal',             pos: 'DEF' },
    { name: 'Mohamed Abdel-Moneim',   pos: 'DEF' },
    { name: 'Akram Tawfik',           pos: 'DEF' },
    { name: 'Tarek Hamed',            pos: 'MID' },
    { name: 'Amr El-Sulaya',          pos: 'MID' },
    { name: 'Omar Marmoush',          pos: 'MID' },
    { name: 'Mohamed Salah',          pos: 'FWD' },
    { name: 'Mostafa Mohamed',        pos: 'FWD' },
    { name: 'Marwan Attia',           pos: 'FWD' },
    { name: 'Ramadan Sobhi',          pos: 'FWD' },
  ],

  // ── Group H ──────────────────────────────────────────────────────────────
  KSA: [
    { name: 'Mohammed Al-Owais',      pos: 'GK'  },
    { name: 'Fawaz Al-Qarni',         pos: 'GK'  },
    { name: 'Ali Al-Bulaihi',         pos: 'DEF' },
    { name: 'Abdulelah Al-Amri',      pos: 'DEF' },
    { name: 'Hassan Tambakti',        pos: 'DEF' },
    { name: 'Saud Abdulhamid',        pos: 'DEF' },
    { name: 'Mohamed Kanno',          pos: 'MID' },
    { name: 'Salman Al-Faraj',        pos: 'MID' },
    { name: 'Abdullah Al-Hamdan',     pos: 'MID' },
    { name: 'Riyadh Sharahili',       pos: 'MID' },
    { name: 'Salem Al-Dawsari',       pos: 'FWD' },
    { name: 'Firas Al-Buraikan',      pos: 'FWD' },
    { name: 'Nasser Al-Dawsari',      pos: 'FWD' },
  ],
  URY: [
    { name: 'Sergio Rochet',          pos: 'GK'  },
    { name: 'Sebastian Sosa',         pos: 'GK'  },
    { name: 'Ronald Araujo',          pos: 'DEF' },
    { name: 'Jose Maria Gimenez',     pos: 'DEF' },
    { name: 'Matias Vina',            pos: 'DEF' },
    { name: 'Nahitan Nandez',         pos: 'DEF' },
    { name: 'Rodrigo Bentancur',      pos: 'MID' },
    { name: 'Federico Valverde',      pos: 'MID' },
    { name: 'Manuel Ugarte',          pos: 'MID' },
    { name: 'Nicolas De La Cruz',     pos: 'MID' },
    { name: 'Luis Suarez',            pos: 'FWD' },
    { name: 'Darwin Nunez',           pos: 'FWD' },
    { name: 'Facundo Pellistri',      pos: 'FWD' },
    { name: 'Maxi Gomez',             pos: 'FWD' },
  ],
  ESP: [
    { name: 'Unai Simon',             pos: 'GK'  },
    { name: 'David Raya',             pos: 'GK'  },
    { name: 'Dani Carvajal',          pos: 'DEF' },
    { name: 'Aymeric Laporte',        pos: 'DEF' },
    { name: 'Pau Torres',             pos: 'DEF' },
    { name: 'Jordi Alba',             pos: 'DEF' },
    { name: 'Robin Le Normand',       pos: 'DEF' },
    { name: 'Rodri',                  pos: 'MID' },
    { name: 'Pedri',                  pos: 'MID' },
    { name: 'Gavi',                   pos: 'MID' },
    { name: 'Dani Olmo',              pos: 'MID' },
    { name: 'Mikel Merino',           pos: 'MID' },
    { name: 'Lamine Yamal',           pos: 'FWD' },
    { name: 'Nico Williams',          pos: 'FWD' },
    { name: 'Alvaro Morata',          pos: 'FWD' },
    { name: 'Ferran Torres',          pos: 'FWD' },
  ],
  CPV: [
    { name: 'Vozinha',                pos: 'GK'  },
    { name: 'Carlos Ponck',           pos: 'DEF' },
    { name: 'Roberto Lopes',          pos: 'DEF' },
    { name: 'Dylan Tavares',          pos: 'DEF' },
    { name: 'Stopira',                pos: 'DEF' },
    { name: 'Ryan Mendes',            pos: 'MID' },
    { name: 'Jamiro Monteiro',        pos: 'MID' },
    { name: 'Garry Rodrigues',        pos: 'MID' },
    { name: 'Lisandro Semedo',        pos: 'MID' },
    { name: 'Ze Luis',                pos: 'FWD' },
    { name: 'Djaniny',                pos: 'FWD' },
    { name: 'Julio Tavares',          pos: 'FWD' },
  ],

  // ── Group I ──────────────────────────────────────────────────────────────
  FRA: [
    { name: 'Mike Maignan',           pos: 'GK'  },
    { name: 'Alphonse Areola',        pos: 'GK'  },
    { name: 'Benjamin Pavard',        pos: 'DEF' },
    { name: 'Theo Hernandez',         pos: 'DEF' },
    { name: 'Lucas Hernandez',        pos: 'DEF' },
    { name: 'William Saliba',         pos: 'DEF' },
    { name: 'Jules Kounde',           pos: 'DEF' },
    { name: 'Aurelien Tchouameni',    pos: 'MID' },
    { name: 'Eduardo Camavinga',      pos: 'MID' },
    { name: 'Adrien Rabiot',          pos: 'MID' },
    { name: 'Warren Zaire-Emery',     pos: 'MID' },
    { name: 'Kylian Mbappe',          pos: 'FWD' },
    { name: 'Antoine Griezmann',      pos: 'FWD' },
    { name: 'Ousmane Dembele',        pos: 'FWD' },
    { name: 'Marcus Thuram',          pos: 'FWD' },
    { name: 'Randal Kolo Muani',      pos: 'FWD' },
  ],
  SEN: [
    { name: 'Edouard Mendy',          pos: 'GK'  },
    { name: 'Alfred Gomis',           pos: 'GK'  },
    { name: 'Kalidou Koulibaly',      pos: 'DEF' },
    { name: 'Abdou Diallo',           pos: 'DEF' },
    { name: 'Youssouf Sabaly',        pos: 'DEF' },
    { name: 'Formose Mendy',          pos: 'DEF' },
    { name: 'Cheikhou Kouyate',       pos: 'MID' },
    { name: 'Idrissa Gueye',          pos: 'MID' },
    { name: 'Pape Matar Sarr',        pos: 'MID' },
    { name: 'Lamine Camara',          pos: 'MID' },
    { name: 'Sadio Mane',             pos: 'FWD' },
    { name: 'Ismaila Sarr',           pos: 'FWD' },
    { name: 'Boulaye Dia',            pos: 'FWD' },
    { name: 'Nicolas Jackson',        pos: 'FWD' },
  ],
  IRQ: [
    { name: 'Jalal Hassan',           pos: 'GK'  },
    { name: 'Mohammed Hameed',        pos: 'GK'  },
    { name: 'Ali Adnan',              pos: 'DEF' },
    { name: 'Amjed Atshan',           pos: 'DEF' },
    { name: 'Rebin Sulaka',           pos: 'DEF' },
    { name: 'Saad Natiq',             pos: 'DEF' },
    { name: 'Safaa Hadi',             pos: 'MID' },
    { name: 'Aymen Hussein',          pos: 'MID' },
    { name: 'Osama Rashid',           pos: 'MID' },
    { name: 'Mohanad Ali',            pos: 'FWD' },
    { name: 'Hussein Ali',            pos: 'FWD' },
    { name: 'Ahmed Yasin',            pos: 'FWD' },
  ],
  NOR: [
    { name: 'Orjan Nyland',           pos: 'GK'  },
    { name: 'Rorvik Brekke',          pos: 'GK'  },
    { name: 'Leo Ostigard',           pos: 'DEF' },
    { name: 'Kristoffer Ajer',        pos: 'DEF' },
    { name: 'Fredrik Aursnes',        pos: 'DEF' },
    { name: 'Birger Meling',          pos: 'DEF' },
    { name: 'Sander Berge',           pos: 'MID' },
    { name: 'Martin Odegaard',        pos: 'MID' },
    { name: 'Mathias Normann',        pos: 'MID' },
    { name: 'Erling Haaland',         pos: 'FWD' },
    { name: 'Alexander Sorloth',      pos: 'FWD' },
    { name: 'Mohamed Elyounoussi',    pos: 'FWD' },
    { name: 'Antonio Nusa',           pos: 'FWD' },
  ],

  // ── Group J ──────────────────────────────────────────────────────────────
  ARG: [
    { name: 'Emiliano Martinez',      pos: 'GK'  },
    { name: 'Franco Armani',          pos: 'GK'  },
    { name: 'Nahuel Molina',          pos: 'DEF' },
    { name: 'Cristian Romero',        pos: 'DEF' },
    { name: 'Lisandro Martinez',      pos: 'DEF' },
    { name: 'Nicolas Tagliafico',     pos: 'DEF' },
    { name: 'Marcos Acuna',           pos: 'DEF' },
    { name: 'Rodrigo De Paul',        pos: 'MID' },
    { name: 'Leandro Paredes',        pos: 'MID' },
    { name: 'Alexis Mac Allister',    pos: 'MID' },
    { name: 'Enzo Fernandez',         pos: 'MID' },
    { name: 'Lionel Messi',           pos: 'FWD' },
    { name: 'Angel Di Maria',         pos: 'FWD' },
    { name: 'Julian Alvarez',         pos: 'FWD' },
    { name: 'Lautaro Martinez',       pos: 'FWD' },
    { name: 'Paulo Dybala',           pos: 'FWD' },
  ],
  ALG: [
    { name: "Rais M'Bolhi",          pos: 'GK'  },
    { name: 'Raed Boucherit',         pos: 'GK'  },
    { name: 'Ramy Bensebaini',        pos: 'DEF' },
    { name: 'Djamel Benlamri',        pos: 'DEF' },
    { name: 'Youcef Atal',            pos: 'DEF' },
    { name: 'Amir Sayoud',            pos: 'DEF' },
    { name: 'Ramiz Zerrouki',         pos: 'MID' },
    { name: 'Houssem Aouar',          pos: 'MID' },
    { name: 'Sofiane Feghouli',       pos: 'MID' },
    { name: 'Ismael Bennacer',        pos: 'MID' },
    { name: 'Baghdad Bounedjah',      pos: 'FWD' },
    { name: 'Said Benrahma',          pos: 'FWD' },
    { name: 'Islam Slimani',          pos: 'FWD' },
    { name: 'Yacine Brahimi',         pos: 'FWD' },
  ],
  AUT: [
    { name: 'Patrick Pentz',          pos: 'GK'  },
    { name: 'Heinz Lindner',          pos: 'GK'  },
    { name: 'David Alaba',            pos: 'DEF' },
    { name: 'Stefan Posch',           pos: 'DEF' },
    { name: 'Philipp Lienhart',       pos: 'DEF' },
    { name: 'Gernot Trauner',         pos: 'DEF' },
    { name: 'Konrad Laimer',          pos: 'MID' },
    { name: 'Nicolas Seiwald',        pos: 'MID' },
    { name: 'Christoph Baumgartner',  pos: 'MID' },
    { name: 'Marcel Sabitzer',        pos: 'MID' },
    { name: 'Florian Grillitsch',     pos: 'MID' },
    { name: 'Marko Arnautovic',       pos: 'FWD' },
    { name: 'Michael Gregoritsch',    pos: 'FWD' },
    { name: 'Patrick Wimmer',         pos: 'FWD' },
  ],
  JOR: [
    { name: 'Yazeed Ababneh',         pos: 'GK'  },
    { name: 'Ahmad Al-Rashdan',       pos: 'GK'  },
    { name: 'Baher Al-Said',          pos: 'DEF' },
    { name: 'Anas Bani-Yaseen',       pos: 'DEF' },
    { name: 'Musa Al-Tamari',         pos: 'DEF' },
    { name: 'Yazan Al-Naimat',        pos: 'MID' },
    { name: 'Ahmad Hamdallah',        pos: 'MID' },
    { name: 'Mahmoud Abu Ruqyah',     pos: 'MID' },
    { name: 'Hamza Al-Dardour',       pos: 'FWD' },
    { name: 'Mousa Al-Taamari',       pos: 'FWD' },
    { name: 'Baha Faisal',            pos: 'FWD' },
  ],

  // ── Group K ──────────────────────────────────────────────────────────────
  POR: [
    { name: 'Diogo Costa',            pos: 'GK'  },
    { name: 'Jose Sa',                pos: 'GK'  },
    { name: 'Joao Cancelo',           pos: 'DEF' },
    { name: 'Ruben Dias',             pos: 'DEF' },
    { name: 'Antonio Silva',          pos: 'DEF' },
    { name: 'Danilo Pereira',         pos: 'DEF' },
    { name: 'Nuno Mendes',            pos: 'DEF' },
    { name: 'Bruno Fernandes',        pos: 'MID' },
    { name: 'Bernardo Silva',         pos: 'MID' },
    { name: 'Joao Neves',             pos: 'MID' },
    { name: 'Vitinha',                pos: 'MID' },
    { name: 'Cristiano Ronaldo',      pos: 'FWD' },
    { name: 'Rafael Leao',            pos: 'FWD' },
    { name: 'Goncalo Ramos',          pos: 'FWD' },
    { name: 'Pedro Neto',             pos: 'FWD' },
    { name: 'Francisco Conceicao',    pos: 'FWD' },
  ],
  COD: [
    { name: 'Joel Kiassumbua',        pos: 'GK'  },
    { name: 'Ley Matampi',            pos: 'GK'  },
    { name: 'Chancel Mbemba',         pos: 'DEF' },
    { name: 'Marcel Tisserand',       pos: 'DEF' },
    { name: 'Ngonda Muzinga',         pos: 'DEF' },
    { name: 'Yannick Bolasie',        pos: 'MID' },
    { name: 'Theo Bongonda',          pos: 'MID' },
    { name: 'Neeskens Kebano',        pos: 'MID' },
    { name: 'Samuel Bastien',         pos: 'MID' },
    { name: 'Cedric Bakambu',         pos: 'FWD' },
    { name: 'Fiston Mayele',          pos: 'FWD' },
    { name: 'Jonathan Bolingi',       pos: 'FWD' },
    { name: 'Dieumerci Mbokani',      pos: 'FWD' },
  ],
  UZB: [
    { name: 'Shukhrat Ergashev',      pos: 'GK'  },
    { name: 'Otabek Shukurov',        pos: 'GK'  },
    { name: 'Jasur Yakhshiboev',      pos: 'DEF' },
    { name: 'Sherzod Nasrullayev',    pos: 'DEF' },
    { name: 'Akbar Tursunov',         pos: 'DEF' },
    { name: 'Dostonbek Khamdamov',    pos: 'MID' },
    { name: 'Jaloliddin Masharipov',  pos: 'MID' },
    { name: 'Otabek Fayzullayev',     pos: 'MID' },
    { name: 'Eldor Shomurodov',       pos: 'FWD' },
    { name: 'Abbosbek Fayzullaev',    pos: 'FWD' },
    { name: 'Khojimat Erkinov',       pos: 'FWD' },
  ],
  COL: [
    { name: 'David Ospina',           pos: 'GK'  },
    { name: 'Camilo Vargas',          pos: 'GK'  },
    { name: 'Davinson Sanchez',       pos: 'DEF' },
    { name: 'Yerry Mina',             pos: 'DEF' },
    { name: 'Johan Mojica',           pos: 'DEF' },
    { name: 'Daniel Munoz',           pos: 'DEF' },
    { name: 'Wilmar Barrios',         pos: 'MID' },
    { name: 'James Rodriguez',        pos: 'MID' },
    { name: 'Richard Rios',           pos: 'MID' },
    { name: 'Luis Diaz',              pos: 'FWD' },
    { name: 'Rafael Santos Borre',    pos: 'FWD' },
    { name: 'Jhon Duran',             pos: 'FWD' },
    { name: 'Juan Cuadrado',          pos: 'MID' },
  ],

  // ── Group L ──────────────────────────────────────────────────────────────
  GHA: [
    { name: 'Lawrence Ati-Zigi',      pos: 'GK'  },
    { name: 'Manaf Nurudeen',         pos: 'GK'  },
    { name: 'Daniel Amartey',         pos: 'DEF' },
    { name: 'Alexander Djiku',        pos: 'DEF' },
    { name: 'Tariq Lamptey',          pos: 'DEF' },
    { name: 'Denis Odoi',             pos: 'DEF' },
    { name: 'Thomas Partey',          pos: 'MID' },
    { name: 'Iddrisu Baba',           pos: 'MID' },
    { name: 'Badu Emmanuel',          pos: 'MID' },
    { name: 'Jordan Ayew',            pos: 'FWD' },
    { name: 'Andre Ayew',             pos: 'FWD' },
    { name: 'Inaki Williams',         pos: 'FWD' },
    { name: 'Osman Bukari',           pos: 'FWD' },
  ],
  PAN: [
    { name: 'Luis Mejia',             pos: 'GK'  },
    { name: 'Orlando Mosquera',       pos: 'GK'  },
    { name: 'Harold Cummings',        pos: 'DEF' },
    { name: 'Fidel Escobar',          pos: 'DEF' },
    { name: 'Eric Davis',             pos: 'DEF' },
    { name: 'Michael Murillo',        pos: 'DEF' },
    { name: 'Andres Andrade',         pos: 'MID' },
    { name: 'Adalberto Carrasquilla', pos: 'MID' },
    { name: 'Anibal Godoy',           pos: 'MID' },
    { name: 'Alberto Quintero',       pos: 'FWD' },
    { name: 'Ismael Diaz',            pos: 'FWD' },
    { name: 'Rolando Blackburn',      pos: 'FWD' },
    { name: 'Cecilio Waterman',       pos: 'FWD' },
  ],
  ENG: [
    { name: 'Jordan Pickford',        pos: 'GK'  },
    { name: 'Nick Pope',              pos: 'GK'  },
    { name: 'Reece James',            pos: 'DEF' },
    { name: 'Kyle Walker',            pos: 'DEF' },
    { name: 'John Stones',            pos: 'DEF' },
    { name: 'Harry Maguire',          pos: 'DEF' },
    { name: 'Luke Shaw',              pos: 'DEF' },
    { name: 'Marc Guehi',             pos: 'DEF' },
    { name: 'Jude Bellingham',        pos: 'MID' },
    { name: 'Declan Rice',            pos: 'MID' },
    { name: 'Conor Gallagher',        pos: 'MID' },
    { name: 'Phil Foden',             pos: 'MID' },
    { name: 'Harry Kane',             pos: 'FWD' },
    { name: 'Bukayo Saka',            pos: 'FWD' },
    { name: 'Marcus Rashford',        pos: 'FWD' },
    { name: 'Raheem Sterling',        pos: 'FWD' },
  ],
  CRO: [
    { name: 'Dominik Livakovic',      pos: 'GK'  },
    { name: 'Ivo Grbic',              pos: 'GK'  },
    { name: 'Josip Juranovic',        pos: 'DEF' },
    { name: 'Dejan Lovren',           pos: 'DEF' },
    { name: 'Josko Gvardiol',         pos: 'DEF' },
    { name: 'Borna Sosa',             pos: 'DEF' },
    { name: 'Marcelo Brozovic',       pos: 'MID' },
    { name: 'Luka Modric',            pos: 'MID' },
    { name: 'Mateo Kovacic',          pos: 'MID' },
    { name: 'Lovro Majer',            pos: 'MID' },
    { name: 'Ante Budimir',           pos: 'FWD' },
    { name: 'Bruno Petkovic',         pos: 'FWD' },
    { name: 'Andrej Kramaric',        pos: 'FWD' },
    { name: 'Marko Livaja',           pos: 'FWD' },
  ],
}

/** Convenience: get squad for a team code, grouped by position. */
export function getSquadByPosition(code: string) {
  const players = SQUADS[code.toUpperCase()] ?? []
  return {
    GK:  players.filter(p => p.pos === 'GK'),
    DEF: players.filter(p => p.pos === 'DEF'),
    MID: players.filter(p => p.pos === 'MID'),
    FWD: players.filter(p => p.pos === 'FWD'),
    total: players.length,
  }
}
